// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ekxmbT4pGN2mFc1KU7PYCnr5yZcaIic',
    appId: '1:498501577733:web:17db1dd1e275266e28006c',
    messagingSenderId: '498501577733',
    projectId: 'reddit-clone-flutter1',
    authDomain: 'reddit-clone-flutter1.firebaseapp.com',
    storageBucket: 'reddit-clone-flutter1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2V_IKRETQJhO49A4GaDou08oSwBR5YJs',
    appId: '1:498501577733:android:006a8a622692f29228006c',
    messagingSenderId: '498501577733',
    projectId: 'reddit-clone-flutter1',
    storageBucket: 'reddit-clone-flutter1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0MHyMPRm7ufzr2v3DSWVScQu1MgAqB4Q',
    appId: '1:498501577733:ios:77a3d4b6721b25f828006c',
    messagingSenderId: '498501577733',
    projectId: 'reddit-clone-flutter1',
    storageBucket: 'reddit-clone-flutter1.appspot.com',
    iosClientId: '498501577733-0id6g6e34f6fh2nsn9epb7e8r2vonsh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneFlutter',
  );
}
